create table T_USER (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(32) NOT NULL,
	CDATE DATETIME,
	PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_USER_USERNAME ON T_USER(USERNAME);

CREATE INDEX IDX_USER_CDATE ON T_USER(CDATE);
