create table T_ORDER (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	ORDER_NBR VARCHAR(32) NOT NULL,
	USER_ID BIGINT NOT NULL,
	CDATE DATETIME,
	PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_ORDER_NBR ON T_ORDER(ORDER_NBR);

CREATE INDEX IDX_ORDER_USER_ID ON T_ORDER(USER_ID);
